In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


# Q.1

In [3]:
import pandas as pd
pd.__version__

'2.2.2'

In [4]:
! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv -O laptops.csv

--2024-09-19 14:52:14--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.02s   

2024-09-19 14:52:14 (14.3 MB/s) - ‘laptops.csv’ saved [298573/298573]



# Q.2

In [5]:
df = pd.read_csv("laptops.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


### 2160 rows

# Q.3

In [6]:
df.Brand.nunique()

27

# Q.4

In [7]:
[c for c in df.columns if df[c].isna().any()]

['Storage type', 'GPU', 'Screen']

# Q.5

In [8]:
df[df.Brand == "Dell"]["Final Price"].max()

np.float64(3936.0)

# Q.6

In [9]:
median = df.Screen.median()

In [10]:
mode = df.Screen.mode()

In [11]:
print(median, mode)

15.6 0    15.6
Name: Screen, dtype: float64


In [12]:
df['Screen'] = df['Screen'].fillna(mode)

In [13]:
df.Screen.median()

np.float64(15.6)

### No

# Q.7

In [26]:
import numpy as np

In [27]:
X = np.array(df[df.Brand == "Innjoo"][['RAM', 'Storage', 'Screen']])

In [28]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [29]:
XTX = X.T.dot(X)

In [30]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [31]:
inv = np.linalg.inv(XTX) 

In [33]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [34]:
w = (inv.dot(X.T)).dot(y)

In [35]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [36]:
w.sum()

np.float64(91.2998806299555)